### PR TITLE
Added Support for Columns with Array(Enum)

### PR DESCRIPTION
**Pull request by sarthak7gupta**

### CODE REVIEW

**Comment by RustyGuard** [comment]
Interesting suggestion, however I would ask you to cover these changes with tests before megring it

**Comment by RustyGuard** [comment]
Hi @sarthak7gupta,
I am thinking of adding this pull request to a new version of the library. 
Do you still have a desire to complete this feature? If so, when do you plan to finish it?

**Comment by sarthak7gupta** [comment]
Hey, sorry for the late reply. Yes, I am working on writing the tests for this. Will need around a week to finish those.

**Comment by RustyGuard** [comment]
@sarthak7gupta, I think that sync_enum_values operation will not work when dealing with enum values wrapped inside of array.
Please tell me whether you fixed it already or I can help you with it.

**Comment by RustyGuard** [comment]
Since there was no activity development is continued in [our brach](https://github.com/Pogchamp-company/alembic-postgresql-enum/tree/feature/12/support-array)

**Review by RustyGuard — APPROVED** [review]

**Pull request closed without merging**
